---
title: "Most Connected"
author: "Ava Swanson"
date: "11/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# top_socially_connected_appearance_in_top4

 output$top_socially_connected_appearance_in_top4 <- renderPlot({
      
      freshmen <- read_csv("data/FINAL_PUBLIC_DATA-4-23-20.csv") %>%
        clean_names() %>%
        mutate(
          id = as.character(id),
          first_id = as.character(first_id),
          second_id = as.character(second_id),
          third_id = as.character(third_id),
          fourth_id = as.character(fourth_id)
        )
      
      myPalette <- brewer.pal(5, "Set2") 
      
      freshmen_satisfaction <- freshmen %>%
        nest(top4 = c(first_id, second_id,
                      third_id, fourth_id)) %>%
        select(id, satisfied, top4) %>%
        mutate(satisfaction_lvl = case_when(satisfied == "Very Satisfied" ~ 2,
                                            satisfied == "Satisfied" ~ 1,
                                            satisfied == "Neutral" ~ 0,
                                            satisfied == "Dissatisfied" ~ -1,
                                            satisfied == "Very Dissatisfied" ~ -2))
      
      # List of all names listed in top 4 friends, with repeats
      
      freshmen_top4_list <- unlist(freshmen_satisfaction$top4)
      
      # Name search function: counts how many times name appeared in list
      
      name_search <- function(name){
        a <- table(freshmen_top4_list)
        
        unname(a[names(a) == name])
      }
      
      # Function takes name input, outputs how many times that name
      # appears in the "most socially connected" column.
      # In other words, how many respondents thought they were the
      # most socially connected person.
      
      well_connected_name_search <- function(name){
        a <- table(freshmen$most_id)
        
        unname(a[names(a) == name])
      }
      
      # Create tibble counting how many times each name appears.
      # Then, arrange tibble to contain top 100 "socially connected" students
      
      well_connected_top <- freshmen %>%
        count(most_id) %>%
        arrange(desc(n)) %>%
        head(100) %>%
        pull(most_id) %>%
        na.omit()
      
      # Create function that checks for outliers using quantile
      
      is_outlier <- function(x) {
        return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
      }
      
      # Create tibble that shows the top 100 "socially connected" students.
      # The tibble has 3 columns:
      # name column: names of top 100 "socially connected" students
      # appearances_in_well_connected column: how many respondents thought this student was the most well connected
      # appearances_in_top4 column: how many respondents listed this student as one of their top 4 friends
      
      well_connected_top_appearances <- tibble(
        id = as.character(well_connected_top),
        appearances_in_top4 = map(id, ~ name_search(.)),
        appearances_in_well_connected = map(id, ~ well_connected_name_search(.))) %>%
        unnest(cols = c(appearances_in_top4, appearances_in_well_connected)) %>%
        mutate(outlierconn = is_outlier(appearances_in_well_connected)) %>%
        mutate(outliertop4 = is_outlier(appearances_in_top4)) %>%
        filter(outlierconn == FALSE & outliertop4 == FALSE)
      
      # Create ggplot
      
      well_connected_top_appearances %>%
        ggplot(aes(x = appearances_in_well_connected, y = appearances_in_top4)) +
        geom_point() +
        
        # Add line of best fit
        
        geom_smooth(method='lm', formula= y~x, color = "skyblue3") +
        
        geom_jitter() +
        
        # Add correlation labels
        
        stat_cor(label.x = 2, label.y = 3.5) +
        labs(
          x = "Number of appearances in 'most socially connected' question",
          y = "Number of appearances in top 4 friend lists",
          title = "Appearances of 'most socially connected' people in top 4 friend lists",
          subtitle = "Most 'socially connected' does not strongly correlate with 'closeness' with the most people"
        ) + theme_economist()
    })

```

```{r}
# Eigen
output$eigen <- render_gt({
      survey_data <- read_csv("data/FINAL_PUBLIC_DATA-4-23-20.csv")
      library(RColorBrewer)
      color <- brewer.pal(4, "Set3")
      edges_full <- survey_data %>% 
        select(id, first_id, second_id, third_id, fourth_id) %>% 
        pivot_longer(cols = c(first_id, second_id, third_id, fourth_id), names_to = "degree", values_to = "endpoint") %>% 
        mutate(colors = case_when(
          degree == "first_id" ~ color[1],
          degree == "second_id" ~ color[2],
          degree == "third_id" ~ color[3],
          degree == "fourth_id" ~ color[4]
        ))
      edges <- edges_full %>% 
        select(id, endpoint)
      nodes <- survey_data %>% 
        select(id) 
      first <- survey_data %>% 
        select(first_id) 
      second <- survey_data %>% 
        select(second_id) 
      third <- survey_data %>% 
        select(third_id) 
      fourth <- survey_data %>% 
        select(fourth_id) 
      all_names <- full_join(fourth, full_join(third, full_join(first, second, by = c("first_id"="second_id")), by=c("third_id" = "first_id")), by=c("fourth_id" = "third_id"))
      nodes <- unique(full_join(nodes, all_names, by=c("id"="fourth_id")))
      g <- graph_from_data_frame(d = edges, vertices = nodes, directed=FALSE)
      
      # Created a tibble showing the eigenvector statistics
      
      eigen <- eigen_centrality(g)
      eigen <- eigen$vector
      
      eigenvector <- tibble(eigen) %>% 
        mutate(eigen_id = nodes$id) %>% 
        arrange(desc(eigen)) %>% 
        filter(eigen_id != 1654) %>% 
        select(eigen_id, eigen)
      
      eigenvector_10 <- eigenvector %>% 
        head(10)
      
      # Created a gt table for the top 10 eigenvector scores
      
      gt(eigenvector_10) %>% 
        tab_header(title = "Top 10 Eigenvector Centrality") %>% 
        cols_label(eigen_id = "ID",
                   eigen = "Eigenvector Score") 
    })
```

```{r}   
# Between
    output$degree <- render_gt({
      survey_data <- read_csv("data/FINAL_PUBLIC_DATA-4-23-20.csv")
      library(RColorBrewer)
      color <- brewer.pal(4, "Set3")
      edges_full <- survey_data %>% 
        select(id, first_id, second_id, third_id, fourth_id) %>% 
        pivot_longer(cols = c(first_id, second_id, third_id, fourth_id), names_to = "degree", values_to = "endpoint") %>% 
        mutate(colors = case_when(
          degree == "first_id" ~ color[1],
          degree == "second_id" ~ color[2],
          degree == "third_id" ~ color[3],
          degree == "fourth_id" ~ color[4]
        ))
      edges <- edges_full %>% 
        select(id, endpoint)
      nodes <- survey_data %>% 
        select(id) 
      first <- survey_data %>% 
        select(first_id) 
      second <- survey_data %>% 
        select(second_id) 
      third <- survey_data %>% 
        select(third_id) 
      fourth <- survey_data %>% 
        select(fourth_id) 
      all_names <- full_join(fourth, full_join(third, full_join(first, second, by = c("first_id"="second_id")), by=c("third_id" = "first_id")), by=c("fourth_id" = "third_id"))
      nodes <- unique(full_join(nodes, all_names, by=c("id"="fourth_id")))
      g <- graph_from_data_frame(d = edges, vertices = nodes, directed=FALSE)
      
      # Made a tibble showing the degree centrality
      
      deg <- degree(g, mode="all")
      
      degree <- tibble(deg) %>% 
        mutate(degree_id = nodes$id) %>% 
        arrange(desc(deg)) %>% 
        filter(degree_id != 1654) %>% 
        select(degree_id, deg)
      
      degree_10 <- degree %>% 
        head(10)
      
      # Created a gt table with the data for degree centrality
      
      gt(degree_10) %>% 
        tab_header(title = "Top 10 Degree Centrality") %>% 
        cols_label(degree_id = "ID",
                   deg = "Number of Connections") 
    })
    
    output$between <- render_gt({
      survey_data <- read_csv("data/FINAL_PUBLIC_DATA-4-23-20.csv")
      library(RColorBrewer)
      color <- brewer.pal(4, "Set3")
      edges_full <- survey_data %>% 
        select(id, first_id, second_id, third_id, fourth_id) %>% 
        pivot_longer(cols = c(first_id, second_id, third_id, fourth_id), names_to = "degree", values_to = "endpoint") %>% 
        mutate(colors = case_when(
          degree == "first_id" ~ color[1],
          degree == "second_id" ~ color[2],
          degree == "third_id" ~ color[3],
          degree == "fourth_id" ~ color[4]
        ))
      edges <- edges_full %>% 
        select(id, endpoint)
      nodes <- survey_data %>% 
        select(id) 
      first <- survey_data %>% 
        select(first_id) 
      second <- survey_data %>% 
        select(second_id) 
      third <- survey_data %>% 
        select(third_id) 
      fourth <- survey_data %>% 
        select(fourth_id) 
      all_names <- full_join(fourth, full_join(third, full_join(first, second, by = c("first_id"="second_id")), by=c("third_id" = "first_id")), by=c("fourth_id" = "third_id"))
      nodes <- unique(full_join(nodes, all_names, by=c("id"="fourth_id")))
      g <- graph_from_data_frame(d = edges, vertices = nodes, directed=FALSE)
      
      # Found the betweenness score of each student
      
      between <- betweenness(g, directed=F, weights=NA, normalized = T)
      
      betweenness <- tibble(between) %>% 
        mutate(between_id = nodes$id) %>% 
        arrange(desc(between)) %>% 
        filter(between_id != 1654) %>% 
        select(between_id, between)
      
      betweenness_10 <- betweenness %>% 
        head(10)
      
      # Created a gt table of the top 10 students with the highest betweenness score
      
      gt(betweenness_10) %>% 
        tab_header(title = "Top 10 Betweenness Centrality") %>% 
        cols_label(between_id = "ID",
                   between = "Betweenness Score") 
    })
``` 

```{r}  
# Close
output$close <- render_gt({
      survey_data <- read_csv("data/FINAL_PUBLIC_DATA-4-23-20.csv") 
      library(RColorBrewer)
      color <- brewer.pal(4, "Set3")
      edges_full <- survey_data %>% 
        select(id, first_id, second_id, third_id, fourth_id) %>% 
        pivot_longer(cols = c(first_id, second_id, third_id, fourth_id), names_to = "degree", values_to = "endpoint") %>% 
        mutate(colors = case_when(
          degree == "first_id" ~ color[1],
          degree == "second_id" ~ color[2],
          degree == "third_id" ~ color[3],
          degree == "fourth_id" ~ color[4]
        ))
      edges <- edges_full %>% 
        select(id, endpoint)
      nodes <- survey_data %>% 
        select(id) 
      first <- survey_data %>% 
        select(first_id) 
      second <- survey_data %>% 
        select(second_id) 
      third <- survey_data %>% 
        select(third_id) 
      fourth <- survey_data %>% 
        select(fourth_id) 
      all_names <- full_join(fourth, full_join(third, full_join(first, second, by = c("first_id"="second_id")), by=c("third_id" = "first_id")), by=c("fourth_id" = "third_id"))
      nodes <- unique(full_join(nodes, all_names, by=c("id"="fourth_id")))
      g <- graph_from_data_frame(d = edges, vertices = nodes, directed=FALSE)
      
      # Found the closeness score of each student
      
      close <- closeness(g, mode="all", weights=NA, normalized=T)
      
      closeness <- tibble(close) %>% 
        mutate(close_id = nodes$id) %>% 
        arrange(desc(close)) %>% 
        filter(close_id != 1654) %>% 
        select(close_id, close)
      
      closeness_10 <- closeness %>% 
        head(10)
      
      # Created a gt table of the top 10 students with the highest closeness score
      
      gt(closeness_10) %>% 
        tab_header(title = "Top 10 Closeness Centrality") %>% 
        cols_label(close_id = "ID",
                   close = "Closeness Score")
    })
```

```{r}
#Top10

output$top10 <- render_gt({
      survey_data <- read_csv("data/FINAL_PUBLIC_DATA-4-23-20.csv") 
      library(RColorBrewer)
      color <- brewer.pal(4, "Set3")
      edges_full <- survey_data %>% 
        select(id, first_id, second_id, third_id, fourth_id) %>% 
        pivot_longer(cols = c(first_id, second_id, third_id, fourth_id), names_to = "degree", values_to = "endpoint") %>% 
        mutate(colors = case_when(
          degree == "first_id" ~ color[1],
          degree == "second_id" ~ color[2],
          degree == "third_id" ~ color[3],
          degree == "fourth_id" ~ color[4]
        ))
      edges <- edges_full %>% 
        select(id, endpoint)
      nodes <- survey_data %>% 
        select(id) 
      first <- survey_data %>% 
        select(first_id) 
      second <- survey_data %>% 
        select(second_id) 
      third <- survey_data %>% 
        select(third_id) 
      fourth <- survey_data %>% 
        select(fourth_id) 
      all_names <- full_join(fourth, full_join(third, full_join(first, second, by = c("first_id"="second_id")), by=c("third_id" = "first_id")), by=c("fourth_id" = "third_id"))
      nodes <- unique(full_join(nodes, all_names, by=c("id"="fourth_id")))
      g <- graph_from_data_frame(d = edges, vertices = nodes, directed=FALSE)
      
      # Identified the top 10 for most socially connected based on the survey
      # Identified the top 10 scores for degree centrality, closeness, betweenness, and eigenvector
      
      most <- survey_data %>% 
        select(most_id) %>% 
        filter(most_id != 1654)
      
      most_10 <- most %>% 
        count(most_id) %>% 
        arrange(desc(n)) %>% 
        head(10) 
      
      deg <- degree(g, mode="all")
      degree <- tibble(deg) %>% 
        mutate(degree_id = nodes$id) %>% 
        arrange(desc(deg)) %>% 
        filter(degree_id != 1654) %>% 
        select(degree_id, deg)
      degree_10 <- degree %>% 
        head(10)
      
      close <- closeness(g, mode="all", weights=NA, normalized=T)
      closeness <- tibble(close) %>% 
        mutate(close_id = nodes$id) %>% 
        arrange(desc(close)) %>% 
        filter(close_id != 1654) %>% 
        select(close_id, close)
      closeness_10 <- closeness %>% 
        head(10)
      
      between <- betweenness(g, directed=F, weights=NA, normalized = T)
      betweenness <- tibble(between) %>% 
        mutate(between_id = nodes$id) %>% 
        arrange(desc(between)) %>% 
        filter(between_id != 1654) %>% 
        select(between_id, between)
      betweenness_10 <- betweenness %>% 
        head(10)
      
      eigen <- eigen_centrality(g)
      eigen <- eigen$vector
      eigenvector <- tibble(eigen) %>% 
        mutate(eigen_id = nodes$id) %>% 
        arrange(desc(eigen)) %>% 
        filter(eigen_id != 1654) %>% 
        select(eigen_id, eigen)
      eigenvector_10 <- eigenvector %>% 
        head(10)
      
      # Specified the top 10 results of each test
      
      most_id_10 <- most_10$most_id
      degree_id_10 <- degree_10$degree_id
      close_id_10 <- closeness_10$close_id
      between_id_10 <- betweenness_10$between_id
      eigen_id_10 <- eigenvector_10$eigen_id
      comp <- tibble(most_id_10, degree_id_10, close_id_10, between_id_10, eigen_id_10) 
      
      # Created a gt table to display all top 10 scores
      
      gt(comp) %>% 
        tab_header(title = "Top 10 ID Comparison") %>% 
        cols_label(most_id_10 = "Survey",
                   eigen_id_10 = "Eigenvector Centrality",
                   degree_id_10 = "Degree Centrality",
                   close_id_10 = "Closeness Centrality",
                   between_id_10 = "Betweenness Centrality") 
    })
```

```{r}
#Degree

output$degree <- render_gt({
      survey_data <- read_csv("data/FINAL_PUBLIC_DATA-4-23-20.csv")
      library(RColorBrewer)
      color <- brewer.pal(4, "Set3")
      edges_full <- survey_data %>% 
        select(id, first_id, second_id, third_id, fourth_id) %>% 
        pivot_longer(cols = c(first_id, second_id, third_id, fourth_id), names_to = "degree", values_to = "endpoint") %>% 
        mutate(colors = case_when(
          degree == "first_id" ~ color[1],
          degree == "second_id" ~ color[2],
          degree == "third_id" ~ color[3],
          degree == "fourth_id" ~ color[4]
        ))
      edges <- edges_full %>% 
        select(id, endpoint)
      nodes <- survey_data %>% 
        select(id) 
      first <- survey_data %>% 
        select(first_id) 
      second <- survey_data %>% 
        select(second_id) 
      third <- survey_data %>% 
        select(third_id) 
      fourth <- survey_data %>% 
        select(fourth_id) 
      all_names <- full_join(fourth, full_join(third, full_join(first, second, by = c("first_id"="second_id")), by=c("third_id" = "first_id")), by=c("fourth_id" = "third_id"))
      nodes <- unique(full_join(nodes, all_names, by=c("id"="fourth_id")))
      g <- graph_from_data_frame(d = edges, vertices = nodes, directed=FALSE)
      
      # Made a tibble showing the degree centrality
      
      deg <- degree(g, mode="all")
      
      degree <- tibble(deg) %>% 
        mutate(degree_id = nodes$id) %>% 
        arrange(desc(deg)) %>% 
        filter(degree_id != 1654) %>% 
        select(degree_id, deg)
      
      degree_10 <- degree %>% 
        head(10)
      
      # Created a gt table with the data for degree centrality
      
      gt(degree_10) %>% 
        tab_header(title = "Top 10 Degree Centrality") %>% 
        cols_label(degree_id = "ID",
                   deg = "Number of Connections") 
    })
```

