---
title: "Elliott_graphs"
author: "Elliott Detjen"
date: "11/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# GRAPHS BELOW

# Jeremiah Mean Satisfaction by Top 4 Comparison
# Location by Virtual Conversion Facet Graph
# Comparing Mean Virtual Conversion Count by Location
# Model with Satisfaction as a Function of Group Size (Virtual Conversion) & On-Campus
# Expectations vs. Reality in Creating Connections (Matching Alignment graph + Popular Mediums)

```

```{r comparison}
# '23 Class vs '24 Class Mean Satisfaction Comparison/Showing up Top 4

library(tidyverse)
library(ggthemes)

      freshmen_satisfaction <- responses_clean %>%
        nest(top4 = c(p1_name, p2_name,
                      p3_name, p4_name)) %>%
        select(id, satisfaction, top4, name)
      
      # List of all names listed in top 4 friends, with repeats
      
      freshmen_top4_list <- unlist(freshmen_satisfaction$top4)
      
      # Calculate overall satisfaction score mean
      
      all_freshmen_satisfaction_mean <- freshmen_satisfaction %>%
        summarize(mean = mean(satisfaction, na.rm = TRUE)) %>%
        pull(mean)
      
      # Create a tibble for comparing satisfaction levels vs. whether or not
      # they appear.
      
      compare_satisfaction <- freshmen_satisfaction %>%
        mutate(appear = name %in% freshmen_top4_list) %>%
        group_by(appear) %>%
        summarize(mean_satis = mean(satisfaction, na.rm = TRUE))
      
      
      compare_satisfaction %>%
        ggplot(aes(x = appear, y = mean_satis, fill = appear)) +
        geom_bar(stat = "identity") + 
        guides(fill=FALSE) +
        scale_x_discrete(labels = c("No", "Yes")) +
        labs(
          x = "Did the respondent's name appear in other respondents' top 4 friends lists?",
          y = "Mean Satisfaction Score",
          title = "Comparing mean satisfaction scores of respondents",
          subtitle = "Respondents who appeared in others lists were more satisfied",
          caption = "Very Dissatisfied = -2, Dissatisfied = -1, Neutral = 0, Satisfied = 1, Very Satisfied = 2"
        ) +
        geom_hline(yintercept = all_freshmen_satisfaction_mean) +
        theme_bw()
      
```

```{r location/group_size, fig.height = 2.5, fig.width= 6} 

off_campus <- responses_clean %>%
  select(location) %>%
  mutate(location = str_replace(location, 
                              pattern = "At Home in US", 
                              replacement = "Off-Campus")) %>%
  mutate(location = str_replace(location, 
                              pattern = "At Home internationally", 
                              replacement = "Off-Campus")) %>%
  mutate(location = str_replace(location, 
                              pattern = "Off-campus in the Cambridge area", 
                              replacement = "Off-Campus")) %>%
  mutate(location = str_replace(location, 
                              pattern = "NA", 
                              replacement = "Off-Campus"))

groupsize_location <- responses_clean %>%
  mutate(location = str_replace(location, 
                              pattern = "At Home in US", 
                              replacement = "Off-Campus")) %>%
  mutate(location = str_replace(location, 
                              pattern = "At Home internationally", 
                              replacement = "Off-Campus")) %>%
  mutate(location = str_replace(location, 
                              pattern = "Off-campus in the Cambridge area", 
                              replacement = "Off-Campus")) %>%
  mutate(location = str_replace(location, 
                              pattern = "NA", 
                              replacement = "Off-Campus")) %>%
    mutate(location = str_replace(location, 
                              pattern = "Apley Court", 
                              replacement = "The Yard")) %>%
  mutate(location = str_replace(location, 
                              pattern = "The Yard", 
                              replacement = "Freshman Housing")) %>%
  mutate(location = str_replace(location, 
                              pattern = "Union Dorm", 
                              replacement = "Freshman Housing")) %>%
  select(satisfaction, group_size, location) %>%
  filter(!is.na(location)) %>%
  mutate_all(~replace(., is.na(.), 0)) %>%
  mutate(satisfaction = as_factor(satisfaction)) %>%
  mutate(group_size = as_factor(group_size)) %>%
  group_by(satisfaction, group_size) %>%
  ggplot(aes(x = group_size, y = after_stat(count / sum(count)), fill = location)) +
  geom_bar(position = "stack", fill = "#6fb4d2") +
  facet_grid(~ location) +
  theme_bw() +
  labs(title = "Comparing Virtual Conversion Counts by Student Location", x = "Virtual to In-Person Conversion Count", y = "Percentage of First Year Class") +
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(size = 7, 
    face=3)) +
  coord_flip() +
  theme(panel.spacing = unit(2, "lines"))


# How to use after_stat to normalize based on each individual facet wrap data graph, not 
# on total count from entire data. 
   

# Have 5 separate graphs. Each titled a "satisfied" variant." X-axis is group
# size, with y being the count of individuals with a discrete group sizes within
# a satisfaction level. Maybe pop in a gganimate. 
# Perhaps do a separate geom_point fully compiled group size vs satisfaction 
# with gganimated coloring by different variables. 
 
```
```{r mean virtual conversions by location graph}

freshmen_location <- responses_clean %>%
    mutate(location = str_replace(location, 
                              pattern = "At Home in US", 
                              replacement = "Off-Campus")) %>%
    mutate(location = str_replace(location, 
                              pattern = "At Home internationally", 
                              replacement = "Off-Campus")) %>%
    mutate(location = str_replace(location, 
                              pattern = "Off-campus in the Cambridge area", 
                              replacement = "Off-Campus")) %>%
    mutate(location = str_replace(location, 
                                pattern = "NA", 
                              replacement = "Off-Campus")) %>%
    mutate(location = str_replace(location, 
                              pattern = "Apley Court", 
                              replacement = "The Yard")) %>%
    mutate(location = str_replace(location, 
                              pattern = "The Yard", 
                              replacement = "Freshman Housing")) %>%
    mutate(location = str_replace(location, 
                              pattern = "Union Dorm", 
                              replacement = "Freshman Housing")) %>%
  select(location, group_size)

# Converting into broader groups of housing.
      
location_gs_means <- freshmen_location %>%
  group_by(location) %>%
  summarize(mean_gs = mean(group_size, na.rm = TRUE)) %>%
  mutate(mean_total = mean(mean_gs))

graph_location_gs_means <- location_gs_means %>%
  ggplot(aes(x = location, y = mean_gs)) +
  geom_bar(stat = "identity", fill = "#6fb4d2") +
  labs(x = "Location",
          y = "Mean Virtual Conversion Count",
          title = "Comparing Mean Virtual Conversion Count by Location",
          subtitle = 
         "Examining the number of virtual contacts converted into in-person connections", 
       caption = "Total Mean of 3.747 Relationships") +
  geom_hline(yintercept = location_gs_means$mean_total) +
  theme_bw()

```

```{r satisfaction/group_size by demographic totals}

#satg_tot

satg_tot <- responses_clean %>%
  select(group_size, satisfaction, gender, pre_o, location, sports, gap_year) %>%
  mutate(gender = str_replace(gender, 
                              pattern = "Genderqueer/Gender Non-Conforming", 
                              replacement = "Other")) %>%
  mutate(gender = str_replace(gender, pattern = "Prefer not to say", 
                              replacement = "Other")) %>%
  group_by(satisfaction, group_size) %>%
  ggplot(aes(x = satisfaction, y = group_size, color = gender)) +
  geom_point() +
  geom_jitter() +
  facet_wrap(~ gender) +
  theme_bw() +
  geom_smooth(formula = y ~ x, se = FALSE, color = "black", method = "loess") +
  labs(x = "Satisfaction Level", y = "Number of Social Conversions", caption = "Very Dissatisfied = -2, Dissatisfied = -1, Neutral = 0, Satisfied = 1, Very Satisfied = 2"
        )
 
 # scale_x_discrete(labels = c("Very \n Dissatisfied",
  #                              "Dissatisfied",
  #                              "Neutral",
  #                              "Satisfied",
  #                              "Very \n Satisfied"))
  # 

satg_tot

```


```{r model}

library(gtsummary)
library(broom.mixed)
library(rstanarm)
library(gt)
library(tidyverse)

model_data <- responses_clean %>%
  mutate(gender = str_replace(gender, 
                              pattern = "Genderqueer/Gender Non-Conforming", 
                              replacement = "Other")) %>%
  mutate(gender = str_replace(gender, pattern = "Prefer not to say", 
                              replacement = "Other")) %>%
  mutate(on_campus = if_else(!location %in% c("At Home (in the US)", "At Home (international student)"), TRUE, FALSE)) %>%
  select(on_campus, gender, satisfaction, group_size)

# group all on campus individuals to be on campus and alternatively

fit_gs <- stan_glm(data = model_data,
                   formula = satisfaction ~ group_size + on_campus + on_campus*group_size - 1,
                   family = gaussian(),
                   refresh = 0)

print(fit_gs, digits = 5)

fit_graph <- fit_gs %>%
  as_tibble() %>%
  ggplot(aes(x = group_size, y = after_stat(count / sum(count)))) +
  geom_histogram(binwidth = 0.01, bins = 100,
                 color = "white", fill = "#6fb4d2") +
  theme_bw()

tbl_regression(fit_gs, intercept = TRUE) %>%
  as_gt() %>%
 # fmt_number(columns = 2:3, decimal = 3) %>%
  tab_header(title = "Regression of Satisfaction",
             subtitle = "The Effect of Group Size and Gender on Satisfaction")


# Interpret + digits + should I graph this? + statistically significant?
# on or off campus, meaningful difference 
# hextable
# fmt_number https://gt.rstudio.com/reference/fmt_number.html

```

```{r}

# Expectations vs. Reality: dissonance1 graph and category ferquency

# Created new dataset that puts all of the ways people met their four people
# into a single column alongside "best way to meet someone" column, location,
# and the how do you stay in contact column.

library(readxl)
library(data.table)
library(tidyverse)

expectations <- read_excel("shiny_app/data/expectations.xlsx")

# TRUE/FALSE Dissonace1 Match Graph

dissonance1 <- expectations %>%
        select(best, p_meet_total) %>%
        mutate(reality = if_else(best %in% p_meet_total, TRUE, FALSE)) %>%
        drop_na() %>%
  ggplot(aes(x = reality)) +
  geom_bar(fill = "#6fb4d2") +
  theme_bw() +
  labs(x = "Matches", y = "Count",
       title = "Frequency of Reality Meeting Expectations",
       subtitle = "Number of matches between speculation and reality on best channels to connect with peers") +
  annotate("text", x = 1, y = 140, label = "84") +
  annotate("text", x = 2, y = 270, label = "246") 

dissonance1

dissonance1_digits <- expectations %>%
        select(best, p_meet_total) %>%
        mutate(reality = if_else(best %in% p_meet_total, TRUE, FALSE)) %>%
        drop_na() %>%
  group_by(reality) %>%
  summarize(sum = sum(reality == TRUE),
            sum2 = sum(reality == FALSE))

###############################################################################

# Top Expectations Graph

top_best_freq <- expectations %>%
  group_by(best) %>%
  tally() %>%
  arrange(desc(n)) %>%
  drop_na() %>%
  slice(1:5)

best_graph <- top_best_freq %>%
  mutate(best = fct_reorder(best, n)) %>%
  ggplot(aes(x = best, y = n / sum(n))) +
  geom_col(fill = "#6fb4d2") +
  theme_bw() +
  labs(title = "Expectations" , subtitle = "How Respondents Speculated on the Best Mediums for Connecting with Peers (Top 5)", y = "Percentage of Respondents",
       x = "Expectation") +
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(size = 8))

# Top Realities Graph

top_pmeet_freq <- expectations %>%
  group_by(p_meet_total) %>%
  tally() %>%
  arrange(desc(n)) %>%
  slice(1:5)

pmeet_graph <- top_pmeet_freq %>%
  mutate(p_meet_total = fct_reorder(p_meet_total, n)) %>%
  ggplot(aes(x = p_meet_total, y = n / sum(n))) +
  geom_col(fill = "#6fb4d2") +
  theme_bw() +
  labs(title = "Reality" , subtitle = "How Respondents Reported Actually Meeting Their Closest 4 Friends (Top 5)",
       x = "Reality",
       y = "Percentage of Respondents") +
    scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(size = 8))

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

# Multiplot function found online by Winston Chang's R Cookbook

multiplot(best_graph, pmeet_graph) %>%
  grid.newpage()
```


