---
title: "Testing Reading Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(tidyverse)
```

```{r}
responses <- read_excel("../shiny_app/raw_data/responses_1.xlsx")

responses_clean <- responses %>%
  rename(gap_year = "1. Have you taken a gap year?",
         location = "2. Where are you living this semester?",
         living = "3. If you are living on campus, are you in a single or do you have suitemates?",
         gender  = "4. Which gender identity do you most identify with?",
         race = "5. Specify your race and/or ethnicity.",
         pre_o = "6. Which pre-orientation program, if any, did you participate in?",
         sports = "7. Are you involved with any sports teams on campus?",
         best = "8. In your opinion, which of the following is best for forming meaningful connections (even if this doesn’t match your own experience)?",
         p1_name = "Name of the first person (first and last)",
         p1_meet = "Where/how did you first meet this person?...10",
         p1_closeness = "How close do you feel to this person on a scale of 1 to 5?...11",
         p2_name = "Name of the second person (first and last)",
         p2_meet = "Where/how did you first meet this person?...13",
         p2_closeness = "How close do you feel to this person on a scale of 1 to 5?...14",
         p3_name = "Name of the third person (first and last)",
         p3_meet = "Where/how did you first meet this person?...16",
         p3_closeness = "How close do you feel to this person on a scale of 1 to 5?...17",
         p4_name = "Name of the fourth person (first and last)",
         p4_meet = "Where/how did you first meet this person?...19",
         p4_closeness = "How close do you feel to this person on a scale of 1 to 5?...20",
         contact = "10. How do you stay in contact with these four people? (If multiple options apply, please pick the primary one.)",
         group_size = "11. How many people have you met virtually that you now often meet up with in-person? (Please enter a single number)",
         in_person = "12. When you do meet with people in-person, where do you go or what do you do? (Please remember that this survey is completely anonymous and your answers will not be used to get you in trouble.)",
         most_connected = "13. Name the person in the Class of 2024 who you think is the most socially connected. (First and last name)",
         satisfaction = "14. How satisfied are you with your social connections with other first-year students at Harvard?",
         name = "First and last name (this won't be linked to your responses ever, we just need to assign you a random ID)"
) %>%
  mutate(id = 1:nrow(responses), .before = 1) %>%
    mutate(satisfaction = str_replace(satisfaction, pattern = "Very Satisfied", replacement = "2")) %>%
  mutate(satisfaction = str_replace(satisfaction, pattern = "Satisfied", replacement = "1")) %>%
  mutate(satisfaction = str_replace(satisfaction, pattern = "Neutral", replacement = "0")) %>%
  mutate(satisfaction = str_replace(satisfaction, pattern = "Dissatisfied", replacement = "-1")) %>%
  mutate(satisfaction = str_replace(satisfaction, pattern = "Very Dissatisfied", replacement = "-2")) %>%
  mutate(satisfaction = str_replace(satisfaction, pattern = "Very -1", replacement = "-2"))

responses_clean$satisfaction <- as.integer(as.character(responses_clean$satisfaction))
responses_clean$group_size <- as.integer(as.character(responses_clean$group_size))
  
```

```{r}
# Getting ids for the p1-p4 columns 

# Does something but no quite it 
id_responses_clean <- responses_clean %>%
   mutate(p1_id = group_indices(., p1_name),
          p2_id = group_indices(., p2_name),
          p3_id = group_indices(., p3_name),
          p4_id = group_indices(., p4_name)) %>%
  select(p1_id, p2_id, p3_id, p4_id, id)

# This doesn't do what I thought it would
id2_responses_clean <- responses_clean %>%
  select(p1_name, p2_name, p3_name, p4_name, id) %>%
  mutate(p1_id = as.factor(p1_name),
         p2_id = as.factor(p2_name),
         p3_id = as.factor(p3_name),
         p4_id = as.factor(p4_name)) %>%
  select(p1_id, p2_id, p3_id, p4_id, id)

# This successfully assign a matching id for the p1-p4 columns!!!
id3_responses_clean <- responses_clean %>%
  select(p1_name, p2_name, p3_name, p4_name, name, most_connected, id) %>%
  pivot_longer(cols = 1:6,
               names_to = "top4",
               values_to = "name") %>%
  mutate(p_id = group_indices(., name)) %>%
  arrange(p_id)
  # pivot_wider(names_from = top4,
  #             values_from = p_id) %>%
  # select(id, p1_name, p2_name, p3_name, p4_name)
```

