---
title: "Testing Graphs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(tidyverse)
library(ggthemes)
library(rstanarm)
library(gt)
library(gtsummary)

#------------------------------------------------------------------------------#
# NB: if you're having trouble with testing and getting the error message
# "object 'responses_final' not found" try running this line here:

responses_final = readRDS("../shiny_app/responses_final.rds")
#------------------------------------------------------------------------------#
```

```{r Best}
best_way <- responses_final %>%
  select(best) %>%
  mutate(count = n()) %>%
  ggplot(aes(x = fct_infreq(best))) +
    geom_col(aes(y = count / sum(count)),
             fill = "#6fb4d2") +
    coord_flip() +
    theme_bw() +
    labs(
      title = "Best Perceived Way \n to Form Connections",
        x = NULL, # "Reported Best Way to Make Connections"
        y = "Percent"
      ) +
      theme(title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 12, face = "plain"),
            axis.title.y = element_text(size = 12, face= "plain")) +
      scale_y_continuous(labels = scales::percent_format())

best_way
```

```{r Meet}
meet_1 <- responses_final %>%
  mutate(meet = p1_meet) %>%
  select(meet)

meet_2 <- responses_final %>%
  mutate(meet = p2_meet) %>%
  select(meet)

meet_3 <- responses_final %>%
  mutate(meet = p3_meet) %>%
  select(meet)

meet_4 <- responses_final %>%
  mutate(meet = p4_meet) %>%
  select(meet)

meet_merged <- rbind(meet_1, meet_2, by = "meet")
meet_merged <- rbind(meet_merged, meet_3, by = "meet")
meet_merged <- rbind(meet_merged, meet_4, by = "meet")

meet <- meet_merged %>%
  mutate(count = n()) %>%
  filter(meet != "NA" & meet != "meet") %>%
  ggplot(aes(x = fct_infreq(meet))) +
    geom_col(aes(y = count / sum(count)),
             fill = "#6fb4d2") +
    coord_flip() +
    theme_bw() +
    labs(
      title = "Way First-Years \n Met Closest Friends",
        x = NULL,
        y = "Percent"
      ) +
      theme(title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 12, face = "plain"),
            axis.title.y = element_text(size = 12, face= "plain")) +
      scale_y_continuous(labels = scales::percent_format())

meet
```

```{r Closeness}
closeness_1 <- responses_final %>%
  mutate(closeness = p1_closeness) %>%
  select(closeness)

closeness_2 <- responses_final %>%
  mutate(closeness = p2_closeness) %>%
  select(closeness)

closeness_3 <- responses_final %>%
  mutate(closeness = p3_closeness) %>%
  select(closeness)

closeness_4 <- responses_final %>%
  mutate(closeness = p4_closeness) %>%
  select(closeness)

closeness_merged <- rbind(closeness_1, closeness_2, by = "closeness")
closeness_merged <- rbind(closeness_merged, closeness_3, by = "closeness")
closeness_merged <- rbind(closeness_merged, closeness_4, by = "closeness")

closeness <- closeness_merged %>%
  filter(closeness != "NA" & closeness != "closeness") %>%
  group_by(closeness) %>%
  summarize(count = n(), .groups = "drop") %>%
  mutate(total = as.numeric(closeness) * count) %>%
  summarize(avg_closeness = sum(total) / sum(count), .groups = "drop")

closeness

# Average closeness is 3.508906
```

```{r Contact}
stay_in_contact <- responses_final %>%
  mutate(contact = as_factor(contact)) %>%
  filter(contact != "NA" & contact != "contact") %>%
  group_by(contact) %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = fct_infreq(contact))) +
      geom_col(aes(y = count / sum(count)),
               fill = "#6fb4d2") +
      theme_bw() +
      coord_flip() +
      theme(legend.position = "none") +
      labs(
        title = "Ways That First-Years \n Stay Connected",
        x = NULL,
        y = "Percent"
      ) +
      theme(title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 12, face = "plain"),
            axis.title.y = element_text(size = 12, face= "plain")) +
      scale_y_continuous(labels = scales::percent_format())

stay_in_contact
```

```{r In-Person}
in_person <- responses_final %>%
  mutate(in_person = as_factor(in_person)) %>%
  filter(in_person != "NA" & in_person != "in_person") %>%
  group_by(in_person) %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = fct_infreq(in_person))) +
      geom_col(aes(y = count / sum(count)),
               fill = "#6fb4d2") +
      theme_bw() +
      coord_flip() +
      theme(legend.position = "none") +
      labs(
        title = "Things That First-Years \n Do In-Person",
        x = NULL,
        y = "Percent"
      ) +
      theme(title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 12, face = "plain"),
            axis.title.y = element_text(size = 12, face= "plain")) +
      scale_y_continuous(labels = scales::percent_format())

in_person
```

```{r Group Size}
group_size <- responses_final %>%
  filter(group_size != "NA" & group_size != "group_size") %>%
  group_by(group_size) %>%
  summarize(count = n(), .groups = "drop") %>%
  mutate(total = as.numeric(group_size) * count) %>%
  summarize(avg_group_size = sum(total) / sum(count), .groups = "drop")

group_size

# Average group size is 4.18299
```

```{r Most Connected Person}
most_connected <- responses_final %>%
  select(most_connected) %>%
  group_by(most_connected) %>%
  summarize(count = n(), .groups = "drop") %>%
  arrange(desc(count)) %>%
  head(10) %>%
  rename("ID" = most_connected,
         "Number of Votes" = count) %>%
  gt() %>%
    tab_header(title = "Top Ten Socially Connected First-Years: Survey")

most_connected
```




```{r Overall Satisfaction}
overall_satisfaction <- responses_test %>%
  mutate(satisfaction = as_factor(satisfaction)) %>%
  filter(satisfaction != "NA") %>%
  group_by(satisfaction) %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = fct_relevel(satisfaction, 
                               levels = c("Very Dissatisfied",
                                          "Dissatisfied",
                                          "Neutral",
                                          "Satisfied",
                                          "Very Satisfied")), 
                 y = count / sum(count))) +
      geom_col(fill = "#6fb4d2") +
      theme_bw() +
      theme(legend.position = "none") +
      labs(
        title = "Overall Satisfaction with Social Connections Among Harvard First-Years",
        x = "Self-Reported Level of Satisfaction with Social Connections",
        y = "Percent"
      ) +
      theme(title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 12, face = "plain"),
            axis.title.y = element_text(size = 12, face= "plain")) +
      scale_y_continuous(labels = scales::percent_format())

overall_satisfaction
```

```{r Satisfaction by Location}
satisfaction_by_location <- responses_test %>%
  mutate(satisfaction = as_factor(satisfaction)) %>%
  filter(satisfaction != "NA") %>%
  select(satisfaction, location) %>%
  filter(location %in% c("The Yard", 
                          "A River House", 
                          "At Home",
                          "The Quad")) %>%
  group_by(satisfaction, location) %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = fct_relevel(satisfaction,
                             levels = c("Very Dissatisfied",
                                          "Dissatisfied",
                                          "Neutral",
                                          "Satisfied",
                                          "Very Satisfied")), 
             y = count / sum(count))) +
  geom_col() +
  facet_wrap(~location) +
  geom_col(fill = "#6fb4d2") +
  theme_bw() +
  labs(title = "Overall Satisfaction with Social Connections \n Among Harvard First-Years by Location",
       x = "Self-Reported Level of Satisfaction with Social Connections",
       y = "Percent") +
  theme(title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12, face = "plain"),
        axis.title.y = element_text(size = 12, face= "plain")) +
  scale_x_discrete(labels = c("Very \n Dissatisfied",
                              "Dissatisfied",
                              "Neutral",
                              "Satisfied",
                              "Very \n Satisfied")) +
  scale_y_continuous(labels = scales::percent_format())

satisfaction_by_location
```

```{r Mean Satisfaction}
satisfaction_summary <- responses_test %>%
  mutate(satisfaction = as_factor(satisfaction)) %>%
  filter(satisfaction != "NA") %>%
  group_by(satisfaction) %>%
  summarize(count = n(), .groups = "drop") %>%
  mutate(satisfaction = str_replace(satisfaction, 
                                    pattern = "Very Satisfied", 
                                    replacement = "2"),
             satisfaction = str_replace(satisfaction, 
                                        pattern = "Very Dissatisfied", 
                                        replacement = "-2"),
             satisfaction = str_replace(satisfaction, 
                                        pattern = "Satisfied", 
                                        replacement = "1"),
             satisfaction = str_replace(satisfaction, 
                                        pattern = "Neutral", 
                                        replacement = "0"),
             satisfaction = str_replace(satisfaction, 
                                        pattern = "Dissatisfied", 
                                        replacement = "-1")) %>%
  mutate(satisfaction = as.numeric(satisfaction)) %>%
  mutate(total = satisfaction * count) %>%
  summarize(avg_satisfaction = sum(total) / sum(count))

# Mean satisfaction is 0.1653944
```

```{r Gap Year Satisfaction}
gap_year_satisfaction <- responses_test %>%
  mutate(satisfaction = as_factor(satisfaction)) %>%
  select(satisfaction, gap_year) %>%
  filter(satisfaction != "NA",
         gap_year == "Yes") %>%
  group_by(satisfaction, gap_year) %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = fct_relevel(satisfaction,
                             levels = c("Very Dissatisfied",
                                          "Dissatisfied",
                                          "Neutral",
                                          "Satisfied",
                                          "Very Satisfied")), 
             y = count / sum(count))) +
  geom_col() +
  geom_col(fill = "#6fb4d2") +
  theme_bw() +
  labs(title = "Overall Satisfaction with Social Connections \n Among Harvard First-Years Who Took a Gap Year Last Year",
       x = "Self-Reported Level of Satisfaction with Social Connections",
       y = "Percent") +
  theme(title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12, face = "plain"),
        axis.title.y = element_text(size = 12, face= "plain")) +
  scale_x_discrete(labels = c("Very \n Dissatisfied",
                              "Dissatisfied",
                              "Neutral",
                              "Satisfied",
                              "Very \n Satisfied")) +
  scale_y_continuous(labels = scales::percent_format())

gap_year_satisfaction
```

```{r Satisfaction by Living Situation}
satisfaction_by_living <- responses_test %>%
  mutate(satisfaction = as_factor(satisfaction)) %>%
  filter(satisfaction != "NA",
         living != "Not Applicable") %>%
  select(satisfaction, living) %>%
  group_by(satisfaction, living) %>%
  summarize(count = n(), .groups = "drop") 

View(satisfaction_by_living)

  ggplot(aes(x = fct_relevel(satisfaction,
                             levels = c("Very Dissatisfied",
                                          "Dissatisfied",
                                          "Neutral",
                                          "Satisfied",
                                          "Very Satisfied")), 
             y = count / sum(count))) +
  geom_col() +
  facet_wrap(~living) +
  geom_col(fill = "#6fb4d2") +
  theme_bw() +
  labs(title = "Overall Satisfaction with Social Connections \n Among Harvard First-Years by Living Situation",
       x = "Self-Reported Level of Satisfaction with Social Connections",
       y = "Percent") +
  theme(title = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 12, face = "plain"),
        axis.title.y = element_text(size = 12, face= "plain")) +
  scale_x_discrete(labels = c("Very \n Dissatisfied",
                              "Dissatisfied",
                              "Neutral",
                              "Satisfied",
                              "Very \n Satisfied")) +
  scale_y_continuous(labels = scales::percent_format())

satisfaction_by_living
```

```{r}
# Predicted Satisfaction Based on Meeting 

set.seed(10)
closeness_model <- stan_glm(p1_closeness ~ p1_meet - 1,
                            data = responses_clean,
                            refresh = 0)

mean_value <- closeness_model %>% 
  as_tibble() %>% 
  pivot_longer(cols = 1:26,
               names_to = "meet",
               values_to = "value") %>%
  filter(meet %in% c("p1_meetZoom lecture", 
                     "p1_meetSocial media (GroupMe, Instagram, Discord, etc.)",
                     "p1_meetIn-person (The courtyard, the line at the dining hall, etc.)")) %>%
  # pull(value) %>%
  group_by(meet) %>%
  summarize(mean = mean(value))

closeness_model %>%
  as_tibble() %>%
  pivot_longer(cols = 1:26,
               names_to = "meet",
               values_to = "value") %>%
  filter(meet %in% c("p1_meetZoom lecture", 
                     "p1_meetSocial media (GroupMe, Instagram, Discord, etc.)",
                     "p1_meetIn-person (The courtyard, the line at the dining hall, etc.)")) %>%
  ggplot(aes(x = value)) +
  geom_histogram(aes(y = after_stat(count/sum(count))), 
                   binwidth = 0.07,
                 fill = "#6fb4d2",
                 color = "white") +
  facet_wrap(~ meet) +
  labs(title = "Posterior Probability Distribution",
         subtitle = "Closeness Based on Meeting",
         x = "Closeness",
         y = "Probability") +
  # geom_vline(xintercept = mean_value,
  #            color = "red") +
  theme_bw()
  
```

