---
title: "Section Regression Work"
author: "Ava Swanson"
date: "11/3/2020"
output: html_document
---

Include  model  that  supplements overall points made in the project
(Could do satisfaction ~ various other factors)
Analysis of probability
Show actual regression and table output ideally, but at least description

```{r setup, include=FALSE}
library(tidyverse)
library(rstanarm)
```

```{r}
responses_clean$gap_yeardummy <- 0 

responses_clean$gap_yeardummy[which(responses_clean$gap_year == "Yes")] <- 1
```

```{r}

fit <- stan_glm(gap_yeardummy ~ p1_closeness + gender + race,
                data = responses_clean,
                refresh = 0,
                family = binomial())

```


```{r}

ggplot(responses_clean, aes(x = group_size)) +
geom_density()

stan_glm(group_size ~ gender + gap_year + living + location,
         data = responses_clean,
         refresh = 0,
         family = poisson())

```

```{r}

# Model: Part 1, (Basic Stan)
# [Satisfaction ~ Group_Size + On_Campus + On_Campus*Group_Size]

# Recitation: How do I graph a posterior with multiple covariates?

library(gtsummary)
library(gt)
library(tidymodels)
library(rstanarm)
library(broom.mixed)

responses_final

model_data <- responses_final %>%
  mutate(gender = str_replace(gender, 
                              pattern = "Genderqueer/Gender Non-Conforming", 
                              replacement = "Other")) %>%
  mutate(gender = str_replace(gender, pattern = "Prefer not to say", 
                              replacement = "Other")) %>%
  mutate(on_campus = if_else(!location %in% c("At Home (in the US)", 
                          "At Home (international student)"), TRUE, FALSE)) %>%
  select(on_campus, gender, satisfaction, group_size) %>%
  mutate(on_campus = as.numeric(on_campus)) %>%
    mutate(satisfaction = str_replace(
      satisfaction, pattern = "Very Satisfied", replacement = "2")) %>%
  mutate(satisfaction = str_replace(
    satisfaction, pattern = "Satisfied", replacement = "1")) %>%
  mutate(satisfaction = str_replace(
    satisfaction, pattern = "Neutral", replacement = "0")) %>%
  mutate(satisfaction = str_replace(
    satisfaction, pattern = "Dissatisfied", replacement = "-1")) %>%
  mutate(satisfaction = str_replace(
    satisfaction, pattern = "Very Dissatisfied", replacement = "-2")) %>%
  mutate(satisfaction = str_replace(
    satisfaction, pattern = "Very -1", replacement = "-2"))

model_data$satisfaction <- as.integer(as.character(model_data$satisfaction))
model_data$group_size <- as.integer(as.character(model_data$group_size))

# Grouped all on campus individuals to be on campus or not. Replaced
# satisfaction levels with an integer value. Grouped extraneous gender
# variants as "Other." Converted Satisfaction and Group_Size values to 
# integers.

fit_gs <- stan_glm(data = model_data,
   formula = satisfaction ~ group_size + on_campus + on_campus:group_size - 1,
   family = gaussian(),
   refresh = 0)

print(fit_gs, digits = 5)

fit_graph <- fit_gs %>%
  as_tibble() %>%
  ggplot(aes(x = group_size, y = after_stat(count / sum(count)))) +
  geom_histogram(binwidth = 0.01, bins = 100,
                 color = "white", fill = "#6fb4d2") +
  theme_bw()

tbl_regression(fit_gs, intercept = TRUE) %>%
  as_gt() %>%
  tab_header(title = "Satisfaction Regression",
             subtitle = 
        "The Effect of Group Size and On-Campus Living on Social Satisfaction")

```

```{r}

# Model: Workflow Edition (Part 2)

# Recitation: Clarify the purpose of this. For reference on efficacy of models
# or is it something that should be shared in the final product?

model_data_split <- initial_split(model_data)
model_data_train <- training(model_data_split)
model_data_test <- testing(model_data_split)
model_data_folds <- vfold_cv(model_data_train, v = 5)

model_wfl <- workflow() %>% 
  add_model(linear_reg() %>% 
              set_engine("lm")) %>% 
  add_recipe(recipe(satisfaction ~ group_size + on_campus,
                    data = model_data_train) %>%
               step_interact(~ group_size:on_campus))

results <- model_wfl %>% 
  fit(data = model_data_train) %>% 
  predict(new_data = model_data_test) %>% 
  bind_cols(model_data_test %>% select(satisfaction)) %>% 
  metrics(truth = satisfaction, estimate = `.pred`)

model_cross <- model_wfl %>% 
  fit_resamples(resamples = model_data_folds) %>% 
  collect_metrics()

```
